###
GET http://localhost:8080/user/TestingUser
Content-Type: application/json

###
POST http://localhost:8080/user/register
Accept: application/json
Content-Type: application/json

{
  "username": "TestingUser",
  "password": "Testing20@",
  "email": "cassiolamarcksilvafreitas@gmail.com"
}

###
POST http://localhost:8080/user/verify/M0q5LGPMCYp1bYGuzcrtPPLtuOLnE4a2znUlR0NtxtY=
Content-Type: application/json

### Login
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "usernameOrEmail": "TestingUser",
  "password": "Testing20@"
}

### Recover
POST http://localhost:8080/user/recover
Content-Type: application/json

{
  "email": "testing@testing.com"
}

